listen = "192.168.1.2"
pull_interval = 30

machines = ["http://dev.crosbymichael.com:4001"]

influx_host = "dev.crosbymichael.com:8086"
influx_database = "citadel"
influx_user = "citadel"
influx_password = "koye"
